<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Equant.SAV2000.ComponentLibrary.MVC</RootNamespace>
    <AssemblyName>Equant.SAV2000.ComponentLibrary.MVC</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <Content Remove="tests\**" />
    <None Remove="tests\**" />
    <Compile Remove="src\**" />
    <Content Remove="src\**" />
    <None Remove="src\**" />
    <EmbeddedResource Remove="src\**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Equant.SAV2000.ComponentLibrary.Common\Equant.SAV2000.ComponentLibrary.Common.csproj" />
  </ItemGroup>

</Project>
