//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equant.SAV2000.ComponentLibrary.Common.Resources
{
    using System;

    /// <summary>
    /// A strongly-typed resource class for looking up localized strings, etc.
    /// </summary>
    public class ApplicationStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal ApplicationStrings()
        {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "Equant.SAV2000.ComponentLibrary.Common.Resources.ApplicationStrings",
                        typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string ACCESS000002
        {
            get { return ResourceManager.GetString("ACCESS000002", resourceCulture); }
        }

        public static string ACCESS000005
        {
            get { return ResourceManager.GetString("ACCESS000005", resourceCulture); }
        }

        public static string ACCESS000006
        {
            get { return ResourceManager.GetString("ACCESS000006", resourceCulture); }
        }

        public static string ACCESS000007
        {
            get { return ResourceManager.GetString("ACCESS000007", resourceCulture); }
        }

        public static string AM
        {
            get { return ResourceManager.GetString("AM", resourceCulture); }
        }

        public static string CleanImageTooltip
        {
            get { return ResourceManager.GetString("CleanImageTooltip", resourceCulture); }
        }

        public static string Datatable_sEmptyTable
        {
            get { return ResourceManager.GetString("Datatable_sEmptyTable", resourceCulture); }
        }

        public static string Datatable_sInfo
        {
            get { return ResourceManager.GetString("Datatable_sInfo", resourceCulture); }
        }

        public static string Datatable_sInfoEmpty
        {
            get { return ResourceManager.GetString("Datatable_sInfoEmpty", resourceCulture); }
        }

        public static string Datatable_sInfoFiltered
        {
            get { return ResourceManager.GetString("Datatable_sInfoFiltered", resourceCulture); }
        }

        public static string Datatable_sInfoThousands
        {
            get { return ResourceManager.GetString("Datatable_sInfoThousands", resourceCulture); }
        }

        public static string Datatable_sLoadingRecords
        {
            get { return ResourceManager.GetString("Datatable_sLoadingRecords", resourceCulture); }
        }

        public static string Datatable_sProcessing
        {
            get { return ResourceManager.GetString("Datatable_sProcessing", resourceCulture); }
        }

        public static string Datatable_sRefreshTime
        {
            get { return ResourceManager.GetString("Datatable_sRefreshTime", resourceCulture); }
        }

        public static string Datatable_sZeroRecords
        {
            get { return ResourceManager.GetString("Datatable_sZeroRecords", resourceCulture); }
        }

        public static string DateImageToolTip
        {
            get { return ResourceManager.GetString("DateImageToolTip", resourceCulture); }
        }

        public static string ERR_DATE_INVALIDE
        {
            get { return ResourceManager.GetString("ERR_DATE_INVALIDE", resourceCulture); }
        }

        public static string ErrorTitle
        {
            get { return ResourceManager.GetString("ErrorTitle", resourceCulture); }
        }

        public static string LBL000011
        {
            get { return ResourceManager.GetString("LBL000011", resourceCulture); }
        }

        public static string LBL000016
        {
            get { return ResourceManager.GetString("LBL000016", resourceCulture); }
        }

        public static string LBL000017
        {
            get { return ResourceManager.GetString("LBL000017", resourceCulture); }
        }

        public static string LBL000021
        {
            get { return ResourceManager.GetString("LBL000021", resourceCulture); }
        }

        public static string LBL000022
        {
            get { return ResourceManager.GetString("LBL000022", resourceCulture); }
        }

        public static string LBL000023
        {
            get { return ResourceManager.GetString("LBL000023", resourceCulture); }
        }

        public static string LBL000024
        {
            get { return ResourceManager.GetString("LBL000024", resourceCulture); }
        }

        public static string LBL000025
        {
            get { return ResourceManager.GetString("LBL000025", resourceCulture); }
        }

        public static string LBL000026
        {
            get { return ResourceManager.GetString("LBL000026", resourceCulture); }
        }

        public static string LBL000027
        {
            get { return ResourceManager.GetString("LBL000027", resourceCulture); }
        }

        public static string LBL000028
        {
            get { return ResourceManager.GetString("LBL000028", resourceCulture); }
        }

        public static string LBL000029
        {
            get { return ResourceManager.GetString("LBL000029", resourceCulture); }
        }

        public static string LBL000030
        {
            get { return ResourceManager.GetString("LBL000030", resourceCulture); }
        }

        public static string LBL000032
        {
            get { return ResourceManager.GetString("LBL000032", resourceCulture); }
        }

        public static string LBL000385
        {
            get { return ResourceManager.GetString("LBL000385", resourceCulture); }
        }

        public static string LBL000911
        {
            get { return ResourceManager.GetString("LBL000911", resourceCulture); }
        }

        public static string LBL000912
        {
            get { return ResourceManager.GetString("LBL000912", resourceCulture); }
        }

        public static string MSG000004
        {
            get { return ResourceManager.GetString("MSG000004", resourceCulture); }
        }

        public static string MSG000491
        {
            get { return ResourceManager.GetString("MSG000491", resourceCulture); }
        }

        public static string MomentFormat
        {
            get { return ResourceManager.GetString("MomentFormat", resourceCulture); }
        }

        public static string MULBL001708
        {
            get { return ResourceManager.GetString("MULBL001708", resourceCulture); }
        }

        public static string MULBL001709
        {
            get { return ResourceManager.GetString("MULBL001709", resourceCulture); }
        }

        public static string MULBL001722
        {
            get { return ResourceManager.GetString("MULBL001722", resourceCulture); }
        }

        public static string MULBL001723
        {
            get { return ResourceManager.GetString("MULBL001723", resourceCulture); }
        }

        public static string MULBL001724
        {
            get { return ResourceManager.GetString("MULBL001724", resourceCulture); }
        }

        public static string MULBL001725
        {
            get { return ResourceManager.GetString("MULBL001725", resourceCulture); }
        }

        public static string PM
        {
            get { return ResourceManager.GetString("PM", resourceCulture); }
        }

        public static string RecordsLimitMessageLong
        {
            get { return ResourceManager.GetString("RecordsLimitMessageLong", resourceCulture); }
        }

        public static string RecordsLimitMessageShort
        {
            get { return ResourceManager.GetString("RecordsLimitMessageShort", resourceCulture); }
        }

        public static string TIP000001
        {
            get { return ResourceManager.GetString("TIP000001", resourceCulture); }
        }

        public static string TIP000010
        {
            get { return ResourceManager.GetString("TIP000010", resourceCulture); }
        }

        public static string TIP000011
        {
            get { return ResourceManager.GetString("TIP000011", resourceCulture); }
        }

        public static string TIP000012
        {
            get { return ResourceManager.GetString("TIP000012", resourceCulture); }
        }

        public static string TIP000013
        {
            get { return ResourceManager.GetString("TIP000013", resourceCulture); }
        }

        public static string TIP000014
        {
            get { return ResourceManager.GetString("TIP000014", resourceCulture); }
        }

        public static string TIP000021
        {
            get { return ResourceManager.GetString("TIP000021", resourceCulture); }
        }

        public static string TIP000022
        {
            get { return ResourceManager.GetString("TIP000022", resourceCulture); }
        }

        public static string TIP000023
        {
            get { return ResourceManager.GetString("TIP000023", resourceCulture); }
        }

        public static string TIP000024
        {
            get { return ResourceManager.GetString("TIP000024", resourceCulture); }
        }

        public static string TIP000025
        {
            get { return ResourceManager.GetString("TIP000025", resourceCulture); }
        }

        public static string TPOAR02F02T77CE11_DATE_DU_JOUR
        {
            get { return ResourceManager.GetString("TPOAR02F02T77CE11_DATE_DU_JOUR", resourceCulture); }
        }

        public static string TPOAR02F02T77CE11_ENTRE
        {
            get { return ResourceManager.GetString("TPOAR02F02T77CE11_ENTRE", resourceCulture); }
        }

        public static string TimeMandatory
        {
            get { return ResourceManager.GetString("TimeMandatory", resourceCulture); }
        }

        public static string Today_Date
        {
            get { return ResourceManager.GetString("Today_Date", resourceCulture); }
        }

        public static string equals_To
        {
            get { return ResourceManager.GetString("equals_To", resourceCulture); }
        }

        public static string lblAsteriks
        {
            get { return ResourceManager.GetString("lblAsteriks", resourceCulture); }
        }

        public static string lblsemiColon
        {
            get { return ResourceManager.GetString("lblsemiColon", resourceCulture); }
        }
    }
}
