//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equant.SAV2000.ComponentLibrary.Common.Resources
{
    using System;

    public class ApplicationStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal ApplicationStrings()
        {
        }

        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "Equant.SAV2000.ComponentLibrary.Common.Resources.ApplicationStrings",
                        typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string TIP000022
        {
            get { return ResourceManager.GetString("TIP000022", resourceCulture) ?? "Call {0}"; }
        }

        public static string lblAsteriks
        {
            get { return ResourceManager.GetString("lblAsteriks", resourceCulture) ?? "*"; }
        }

        public static string lblsemiColon
        {
            get { return ResourceManager.GetString("lblsemiColon", resourceCulture) ?? ":"; }
        }
    }
}
